.TH "FLProgW5100TcpDevice" 3 "Чт 23 Фев 2023" "Version 1" "FLProg Utilites" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLProgW5100TcpDevice
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <flprogTcpDevice\&.h>\fP
.PP
Базовые классы:\fBFLProgTcpDevice\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "virtual void \fBbegin\fP ()"
.br
.ti -1c
.RI "virtual bool \fBhasClient\fP ()"
.br
.ti -1c
.RI "virtual bool \fBhasServer\fP ()"
.br
.in -1c

Открытые члены унаследованные от \fBFLProgTcpDevice\fP
.in +1c
.ti -1c
.RI "void \fBbeClient\fP ()"
.br
.ti -1c
.RI "void \fBbeServer\fP ()"
.br
.ti -1c
.RI "byte \fBavailable\fP ()"
.br
.ti -1c
.RI "byte \fBread\fP ()"
.br
.ti -1c
.RI "void \fBsetPort\fP (int port)"
.br
.ti -1c
.RI "bool \fBconnected\fP ()"
.br
.ti -1c
.RI "void \fBconnect\fP ()"
.br
.ti -1c
.RI "void \fBconnect\fP (byte ipFirst, byte ipSecond, byte ipThird, byte ipFourth)"
.br
.ti -1c
.RI "virtual void \fBconnect\fP (uint16_t ipFirst, uint16_t ipSecond, uint16_t ipThird, uint16_t ipFourth, int newPort)"
.br
.ti -1c
.RI "virtual void \fBconnect\fP (IPAddress newIp, int newPort)"
.br
.ti -1c
.RI "void \fBprint\fP (String data)"
.br
.ti -1c
.RI "byte \fBwrite\fP (byte buffer[], byte size)"
.br
.ti -1c
.RI "virtual void \fBbegin\fP ()"
.br
.ti -1c
.RI "void \fBrestart\fP ()"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "virtual bool \fBhasClient\fP ()"
.br
.ti -1c
.RI "virtual bool \fBhasServer\fP ()"
.br
.in -1c
.SS "Защищенные члены"

.in +1c
.ti -1c
.RI "virtual Client * \fBtcpClient\fP ()"
.br
.ti -1c
.RI "virtual void \fBsetAvalibleClientFromServer\fP ()"
.br
.ti -1c
.RI "virtual IPAddress \fBclientRemoteIp\fP ()"
.br
.ti -1c
.RI "virtual int \fBclientRemotePort\fP ()"
.br
.in -1c
.in +1c
.ti -1c
.RI "virtual Client * \fBtcpClient\fP ()"
.br
.ti -1c
.RI "virtual void \fBsetAvalibleClientFromServer\fP ()"
.br
.ti -1c
.RI "virtual IPAddress \fBclientRemoteIp\fP ()"
.br
.ti -1c
.RI "virtual int \fBclientRemotePort\fP ()"
.br
.in -1c
.SS "Дополнительные унаследованные члены"


Защищенные данные унаследованные от \fBFLProgTcpDevice\fP
.in +1c
.ti -1c
.RI "bool \fBmode\fP = \fBFLPROG_TSP_CLIENT_MODE\fP"
.br
.ti -1c
.RI "int \fBtcpPort\fP = 502"
.br
.ti -1c
.RI "IPAddress \fBworkIp\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле \fBflprogTcpDevice\&.h\fP строка \fB51\fP
.SH "Методы"
.PP 
.SS "void FLProgW5100TcpDevice::begin ()\fC [virtual]\fP"

.PP
Переопределяет метод предка \fBFLProgTcpDevice\fP\&.
.PP
См\&. определение в файле \fBflprogTcpDevice\&.cpp\fP строка \fB108\fP
.SS "virtual IPAddress FLProgW5100TcpDevice::clientRemoteIp ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Переопределяет метод предка \fBFLProgTcpDevice\fP\&.
.PP
См\&. определение в файле \fBflprogTcpDevice\&.h\fP строка \fB61\fP
.SS "virtual int FLProgW5100TcpDevice::clientRemotePort ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Переопределяет метод предка \fBFLProgTcpDevice\fP\&.
.PP
См\&. определение в файле \fBflprogTcpDevice\&.h\fP строка \fB62\fP
.SS "virtual bool FLProgW5100TcpDevice::hasClient ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Переопределяет метод предка \fBFLProgTcpDevice\fP\&.
.PP
См\&. определение в файле \fBflprogTcpDevice\&.h\fP строка \fB55\fP
.SS "virtual bool FLProgW5100TcpDevice::hasServer ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Переопределяет метод предка \fBFLProgTcpDevice\fP\&.
.PP
См\&. определение в файле \fBflprogTcpDevice\&.h\fP строка \fB56\fP
.SS "void FLProgW5100TcpDevice::setAvalibleClientFromServer ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Переопределяет метод предка \fBFLProgTcpDevice\fP\&.
.PP
См\&. определение в файле \fBflprogTcpDevice\&.cpp\fP строка \fB117\fP
.SS "virtual Client * FLProgW5100TcpDevice::tcpClient ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Переопределяет метод предка \fBFLProgTcpDevice\fP\&.
.PP
См\&. определение в файле \fBflprogTcpDevice\&.h\fP строка \fB59\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для FLProg Utilites из исходного текста\&.
