.TH "FLProgI2cBasicSensor" 3 "Чт 23 Фев 2023" "Version 1" "FLProg Utilites" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLProgI2cBasicSensor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <flprogI2C_sensorsBasic\&.h>\fP
.PP
Производные классы:\fBFLProgI2cStepWorkSensor\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "uint8_t \fBgetError\fP ()"
.br
.in -1c
.SS "Защищенные данные"

.in +1c
.ti -1c
.RI "\fBFLProgI2C\fP * \fBi2cDevice\fP"
.br
.ti -1c
.RI "uint8_t \fBaddres\fP"
.br
.ti -1c
.RI "uint32_t \fBspeed\fP = \fBFLPROG_I2CSPEED\fP"
.br
.ti -1c
.RI "uint8_t \fBcodeError\fP = \fBFLPROG_SENSOR_NOT_ERROR\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле \fBflprogI2C_sensorsBasic\&.h\fP строка \fB5\fP
.SH "Методы"
.PP 
.SS "uint8_t FLProgI2cBasicSensor::getError ()\fC [inline]\fP"

.PP
См\&. определение в файле \fBflprogI2C_sensorsBasic\&.h\fP строка \fB8\fP
.SH "Данные класса"
.PP 
.SS "uint8_t FLProgI2cBasicSensor::addres\fC [protected]\fP"

.PP
См\&. определение в файле \fBflprogI2C_sensorsBasic\&.h\fP строка \fB12\fP
.SS "uint8_t FLProgI2cBasicSensor::codeError = \fBFLPROG_SENSOR_NOT_ERROR\fP\fC [protected]\fP"

.PP
См\&. определение в файле \fBflprogI2C_sensorsBasic\&.h\fP строка \fB14\fP
.SS "\fBFLProgI2C\fP* FLProgI2cBasicSensor::i2cDevice\fC [protected]\fP"

.PP
См\&. определение в файле \fBflprogI2C_sensorsBasic\&.h\fP строка \fB11\fP
.SS "uint32_t FLProgI2cBasicSensor::speed = \fBFLPROG_I2CSPEED\fP\fC [protected]\fP"

.PP
См\&. определение в файле \fBflprogI2C_sensorsBasic\&.h\fP строка \fB13\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для FLProg Utilites из исходного текста\&.
