.TH "src/tcp/flprogTcpDevice.h" 3 "Чт 23 Фев 2023" "Version 1" "FLProg Utilites" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tcp/flprogTcpDevice.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Arduino\&.h'\fP
.br
\fC#include '\&./flprogUtilites\&.h'\fP
.br
\fC#include 'Ethernet\&.h'\fP
.br
\fC#include 'SPI\&.h'\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBFLProgTcpDevice\fP"
.br
.ti -1c
.RI "class \fBFLProgW5100TcpDevice\fP"
.br
.in -1c
.SS "Макросы"

.in +1c
.ti -1c
.RI "#define \fBFLPROG_TCP_SERVER_MODE\fP   1"
.br
.ti -1c
.RI "#define \fBFLPROG_TSP_CLIENT_MODE\fP   0"
.br
.in -1c
.SH "Макросы"
.PP 
.SS "#define FLPROG_TCP_SERVER_MODE   1"

.PP
См\&. определение в файле \fBflprogTcpDevice\&.h\fP строка \fB14\fP
.SS "#define FLPROG_TSP_CLIENT_MODE   0"

.PP
См\&. определение в файле \fBflprogTcpDevice\&.h\fP строка \fB15\fP
.SH "Автор"
.PP 
Автоматически создано Doxygen для FLProg Utilites из исходного текста\&.
