.TH "FLProgTcpDevice" 3 "Чт 23 Фев 2023" "Version 1" "FLProg Utilites" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLProgTcpDevice
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <flprogTcpDevice\&.h>\fP
.PP
Производные классы:\fBFLProgW5100TcpDevice\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "void \fBbeClient\fP ()"
.br
.ti -1c
.RI "void \fBbeServer\fP ()"
.br
.ti -1c
.RI "byte \fBavailable\fP ()"
.br
.ti -1c
.RI "byte \fBread\fP ()"
.br
.ti -1c
.RI "void \fBsetPort\fP (int port)"
.br
.ti -1c
.RI "bool \fBconnected\fP ()"
.br
.ti -1c
.RI "void \fBconnect\fP ()"
.br
.ti -1c
.RI "void \fBconnect\fP (byte ipFirst, byte ipSecond, byte ipThird, byte ipFourth)"
.br
.ti -1c
.RI "virtual void \fBconnect\fP (uint16_t ipFirst, uint16_t ipSecond, uint16_t ipThird, uint16_t ipFourth, int newPort)"
.br
.ti -1c
.RI "virtual void \fBconnect\fP (IPAddress newIp, int newPort)"
.br
.ti -1c
.RI "void \fBprint\fP (String data)"
.br
.ti -1c
.RI "byte \fBwrite\fP (byte buffer[], byte size)"
.br
.ti -1c
.RI "virtual void \fBbegin\fP ()"
.br
.ti -1c
.RI "void \fBrestart\fP ()"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "virtual bool \fBhasClient\fP ()"
.br
.ti -1c
.RI "virtual bool \fBhasServer\fP ()"
.br
.in -1c
.SS "Защищенные члены"

.in +1c
.ti -1c
.RI "virtual Client * \fBtcpClient\fP ()"
.br
.ti -1c
.RI "virtual void \fBsetAvalibleClientFromServer\fP ()"
.br
.ti -1c
.RI "virtual IPAddress \fBclientRemoteIp\fP ()"
.br
.ti -1c
.RI "virtual int \fBclientRemotePort\fP ()"
.br
.in -1c
.SS "Защищенные данные"

.in +1c
.ti -1c
.RI "bool \fBmode\fP = \fBFLPROG_TSP_CLIENT_MODE\fP"
.br
.ti -1c
.RI "int \fBtcpPort\fP = 502"
.br
.ti -1c
.RI "IPAddress \fBworkIp\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле \fBflprogTcpDevice\&.h\fP строка \fB17\fP
.SH "Методы"
.PP 
.SS "byte FLProgTcpDevice::available ()"

.PP
См\&. определение в файле \fBflprogTcpDevice\&.cpp\fP строка \fB41\fP
.SS "void FLProgTcpDevice::beClient ()"

.PP
См\&. определение в файле \fBflprogTcpDevice\&.cpp\fP строка \fB11\fP
.SS "virtual void FLProgTcpDevice::begin ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Переопределяется в \fBFLProgW5100TcpDevice\fP\&.
.PP
См\&. определение в файле \fBflprogTcpDevice\&.h\fP строка \fB32\fP
.SS "void FLProgTcpDevice::beServer ()"

.PP
См\&. определение в файле \fBflprogTcpDevice\&.cpp\fP строка \fB19\fP
.SS "virtual IPAddress FLProgTcpDevice::clientRemoteIp ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Переопределяется в \fBFLProgW5100TcpDevice\fP\&.
.PP
См\&. определение в файле \fBflprogTcpDevice\&.h\fP строка \fB43\fP
.SS "virtual int FLProgTcpDevice::clientRemotePort ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Переопределяется в \fBFLProgW5100TcpDevice\fP\&.
.PP
См\&. определение в файле \fBflprogTcpDevice\&.h\fP строка \fB44\fP
.SS "void FLProgTcpDevice::connect ()\fC [inline]\fP"

.PP
См\&. определение в файле \fBflprogTcpDevice\&.h\fP строка \fB26\fP
.SS "void FLProgTcpDevice::connect (byte ipFirst, byte ipSecond, byte ipThird, byte ipFourth)\fC [inline]\fP"

.PP
См\&. определение в файле \fBflprogTcpDevice\&.h\fP строка \fB27\fP
.SS "void FLProgTcpDevice::connect (IPAddress newIp, int newPort)\fC [virtual]\fP"

.PP
См\&. определение в файле \fBflprogTcpDevice\&.cpp\fP строка \fB81\fP
.SS "void FLProgTcpDevice::connect (uint16_t ipFirst, uint16_t ipSecond, uint16_t ipThird, uint16_t ipFourth, int newPort)\fC [virtual]\fP"

.PP
См\&. определение в файле \fBflprogTcpDevice\&.cpp\fP строка \fB71\fP
.SS "bool FLProgTcpDevice::connected ()"

.PP
См\&. определение в файле \fBflprogTcpDevice\&.cpp\fP строка \fB56\fP
.SS "virtual bool FLProgTcpDevice::hasClient ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Переопределяется в \fBFLProgW5100TcpDevice\fP\&.
.PP
См\&. определение в файле \fBflprogTcpDevice\&.h\fP строка \fB35\fP
.SS "virtual bool FLProgTcpDevice::hasServer ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Переопределяется в \fBFLProgW5100TcpDevice\fP\&.
.PP
См\&. определение в файле \fBflprogTcpDevice\&.h\fP строка \fB36\fP
.SS "void FLProgTcpDevice::print (String data)"

.PP
См\&. определение в файле \fBflprogTcpDevice\&.cpp\fP строка \fB61\fP
.SS "byte FLProgTcpDevice::read ()"

.PP
См\&. определение в файле \fBflprogTcpDevice\&.cpp\fP строка \fB50\fP
.SS "void FLProgTcpDevice::restart ()"

.PP
См\&. определение в файле \fBflprogTcpDevice\&.cpp\fP строка \fB27\fP
.SS "virtual void FLProgTcpDevice::setAvalibleClientFromServer ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Переопределяется в \fBFLProgW5100TcpDevice\fP\&.
.PP
См\&. определение в файле \fBflprogTcpDevice\&.h\fP строка \fB42\fP
.SS "void FLProgTcpDevice::setPort (int port)"

.PP
См\&. определение в файле \fBflprogTcpDevice\&.cpp\fP строка \fB3\fP
.SS "void FLProgTcpDevice::stop ()"

.PP
См\&. определение в файле \fBflprogTcpDevice\&.cpp\fP строка \fB36\fP
.SS "virtual Client * FLProgTcpDevice::tcpClient ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Переопределяется в \fBFLProgW5100TcpDevice\fP\&.
.PP
См\&. определение в файле \fBflprogTcpDevice\&.h\fP строка \fB41\fP
.SS "byte FLProgTcpDevice::write (byte buffer[], byte size)"

.PP
См\&. определение в файле \fBflprogTcpDevice\&.cpp\fP строка \fB66\fP
.SH "Данные класса"
.PP 
.SS "bool FLProgTcpDevice::mode = \fBFLPROG_TSP_CLIENT_MODE\fP\fC [protected]\fP"

.PP
См\&. определение в файле \fBflprogTcpDevice\&.h\fP строка \fB39\fP
.SS "int FLProgTcpDevice::tcpPort = 502\fC [protected]\fP"

.PP
См\&. определение в файле \fBflprogTcpDevice\&.h\fP строка \fB40\fP
.SS "IPAddress FLProgTcpDevice::workIp\fC [protected]\fP"

.PP
См\&. определение в файле \fBflprogTcpDevice\&.h\fP строка \fB45\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для FLProg Utilites из исходного текста\&.
