.TH "src/uart/flprogUart.h" 3 "Чт 23 Фев 2023" "Version 1" "FLProg Utilites" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/uart/flprogUart.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Arduino\&.h'\fP
.br
\fC#include 'flprogUtilites\&.h'\fP
.br
\fC#include 'softwareUart\\flprogSoftwareUart\&.h'\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBFLProgUartBasic\fP"
.br
.in -1c
.SS "Макросы"

.in +1c
.ti -1c
.RI "#define \fBFLPROG_CAN_USE_SOFTWARE_SERIAL\fP"
.br
.ti -1c
.RI "#define \fBFLPROG_HARDWARE_UART\fP   0"
.br
.ti -1c
.RI "#define \fBFLPROG_USB_UART\fP   1"
.br
.ti -1c
.RI "#define \fBFLPROG_SPEED_300\fP   0"
.br
.ti -1c
.RI "#define \fBFLPROG_SPEED_600\fP   1"
.br
.ti -1c
.RI "#define \fBFLPROG_SPEED_1200\fP   2"
.br
.ti -1c
.RI "#define \fBFLPROG_SPEED_2400\fP   3"
.br
.ti -1c
.RI "#define \fBFLPROG_SPEED_4800\fP   4"
.br
.ti -1c
.RI "#define \fBFLPROG_SPEED_9600\fP   5"
.br
.ti -1c
.RI "#define \fBFLPROG_SPEED_14400\fP   6"
.br
.ti -1c
.RI "#define \fBFLPROG_SPEED_19200\fP   7"
.br
.ti -1c
.RI "#define \fBFLPROG_SPEED_28800\fP   8"
.br
.ti -1c
.RI "#define \fBFLPROG_SPEED_38400\fP   9"
.br
.ti -1c
.RI "#define \fBFLPROG_SPEED_57600\fP   10"
.br
.ti -1c
.RI "#define \fBFLPROG_SPEED_115200\fP   11"
.br
.ti -1c
.RI "#define \fBFLPROG_PORT_STOP_BITS_1\fP   1"
.br
.ti -1c
.RI "#define \fBFLPROG_PORT_STOP_BITS_2\fP   2"
.br
.ti -1c
.RI "#define \fBFLPROG_PORT_DATA_BITS_5\fP   5"
.br
.ti -1c
.RI "#define \fBFLPROG_PORT_DATA_BITS_6\fP   6"
.br
.ti -1c
.RI "#define \fBFLPROG_PORT_DATA_BITS_7\fP   7"
.br
.ti -1c
.RI "#define \fBFLPROG_PORT_DATA_BITS_8\fP   8"
.br
.ti -1c
.RI "#define \fBFLPROG_PORT_PARITY_NONE\fP   0"
.br
.ti -1c
.RI "#define \fBFLPROG_PORT_PARITY_EVEN\fP   1"
.br
.ti -1c
.RI "#define \fBFLPROG_PORT_PARITY_ODD\fP   2"
.br
.in -1c
.SH "Макросы"
.PP 
.SS "#define FLPROG_CAN_USE_SOFTWARE_SERIAL"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB8\fP
.SS "#define FLPROG_HARDWARE_UART   0"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB17\fP
.SS "#define FLPROG_PORT_DATA_BITS_5   5"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB36\fP
.SS "#define FLPROG_PORT_DATA_BITS_6   6"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB37\fP
.SS "#define FLPROG_PORT_DATA_BITS_7   7"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB38\fP
.SS "#define FLPROG_PORT_DATA_BITS_8   8"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB39\fP
.SS "#define FLPROG_PORT_PARITY_EVEN   1"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB42\fP
.SS "#define FLPROG_PORT_PARITY_NONE   0"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB41\fP
.SS "#define FLPROG_PORT_PARITY_ODD   2"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB43\fP
.SS "#define FLPROG_PORT_STOP_BITS_1   1"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB33\fP
.SS "#define FLPROG_PORT_STOP_BITS_2   2"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB34\fP
.SS "#define FLPROG_SPEED_115200   11"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB31\fP
.SS "#define FLPROG_SPEED_1200   2"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB22\fP
.SS "#define FLPROG_SPEED_14400   6"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB26\fP
.SS "#define FLPROG_SPEED_19200   7"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB27\fP
.SS "#define FLPROG_SPEED_2400   3"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB23\fP
.SS "#define FLPROG_SPEED_28800   8"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB28\fP
.SS "#define FLPROG_SPEED_300   0"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB20\fP
.SS "#define FLPROG_SPEED_38400   9"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB29\fP
.SS "#define FLPROG_SPEED_4800   4"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB24\fP
.SS "#define FLPROG_SPEED_57600   10"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB30\fP
.SS "#define FLPROG_SPEED_600   1"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB21\fP
.SS "#define FLPROG_SPEED_9600   5"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB25\fP
.SS "#define FLPROG_USB_UART   1"

.PP
См\&. определение в файле \fBflprogUart\&.h\fP строка \fB18\fP
.SH "Автор"
.PP 
Автоматически создано Doxygen для FLProg Utilites из исходного текста\&.
