.TH "FLProgVirtualI2C" 3 "Чт 23 Фев 2023" "Version 1" "FLProg Utilites" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLProgVirtualI2C
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <flprogI2C\&.h>\fP
.PP
Базовые классы:\fBFLProgI2C\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBFLProgVirtualI2C\fP (\fBFLProgTCA9548A\fP *parentDevice, uint8_t chanelOnParent)"
.br
.ti -1c
.RI "virtual bool \fBbegin\fP ()"
.br
.ti -1c
.RI "virtual void \fBbeginTransmission\fP (uint8_t addr)"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (const uint8_t *data, uint8_t quantity)"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (uint8_t data)"
.br
.ti -1c
.RI "virtual uint8_t \fBendTransmission\fP ()"
.br
.ti -1c
.RI "virtual int \fBavailable\fP ()"
.br
.ti -1c
.RI "virtual int \fBread\fP ()"
.br
.ti -1c
.RI "virtual uint8_t \fBrequestFrom\fP (uint8_t address, uint8_t quantity)"
.br
.ti -1c
.RI "virtual void \fBsetSpeed\fP (uint32_t newSpeed)"
.br
.ti -1c
.RI "virtual void \fBresetSpeedFrom\fP (uint32_t newSpeed)"
.br
.ti -1c
.RI "virtual bool \fBcheckBus\fP ()"
.br
.in -1c

Открытые члены унаследованные от \fBFLProgI2C\fP
.in +1c
.ti -1c
.RI "\fBFLProgI2C\fP (byte busNumber=0)"
.br
.ti -1c
.RI "virtual bool \fBbegin\fP ()"
.br
.ti -1c
.RI "bool \fBbegin\fP (int pinSDA, int pinSCL)"
.br
.ti -1c
.RI "bool \fBfindAddr\fP (uint8_t addr)"
.br
.ti -1c
.RI "uint8_t \fBgetErrorCode\fP ()"
.br
.ti -1c
.RI "uint8_t \fBfullWrite\fP (uint8_t addr, uint8_t data)"
.br
.ti -1c
.RI "uint8_t \fBfullWrite\fP (uint8_t addr, const uint8_t *data, uint8_t quantity)"
.br
.ti -1c
.RI "uint8_t \fBfullRequestFrom\fP (uint8_t address, uint8_t quantity)"
.br
.ti -1c
.RI "uint8_t \fBfullRead\fP (uint8_t addr, uint8_t *data, uint8_t quantity)"
.br
.ti -1c
.RI "uint8_t \fBfullRead\fP (uint8_t addr, uint16_t *data, uint8_t quantity)"
.br
.ti -1c
.RI "uint8_t \fBfullRead\fP (uint8_t addr, uint32_t *data, uint8_t quantity)"
.br
.ti -1c
.RI "uint8_t \fBfullReadReg\fP (uint8_t addr, uint8_t reg)"
.br
.ti -1c
.RI "uint8_t \fBfullWriteReg\fP (uint8_t addr, uint8_t reg, uint8_t value)"
.br
.ti -1c
.RI "virtual void \fBbeginTransmission\fP (uint8_t addr)"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (const uint8_t *data, uint8_t quantity)"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (uint8_t data)"
.br
.ti -1c
.RI "virtual uint8_t \fBendTransmission\fP ()"
.br
.ti -1c
.RI "virtual int \fBavailable\fP ()"
.br
.ti -1c
.RI "virtual int \fBread\fP ()"
.br
.ti -1c
.RI "virtual uint8_t \fBrequestFrom\fP (uint8_t address, uint8_t quantity)"
.br
.ti -1c
.RI "virtual uint8_t \fBwaitingForData\fP (uint8_t count)"
.br
.ti -1c
.RI "virtual void \fBsetSpeed\fP (uint32_t newSpeed)"
.br
.ti -1c
.RI "virtual void \fBresetSpeedFrom\fP (uint32_t newSpeed)"
.br
.ti -1c
.RI "virtual bool \fBcheckBus\fP ()"
.br
.in -1c
.SS "Дополнительные унаследованные члены"


Защищенные члены унаследованные от \fBFLProgI2C\fP
.in +1c
.ti -1c
.RI "bool \fBbeginWire0\fP ()"
.br
.in -1c

Защищенные данные унаследованные от \fBFLProgI2C\fP
.in +1c
.ti -1c
.RI "uint8_t \fBbus\fP"
.br
.ti -1c
.RI "bool \fBbusy\fP = false"
.br
.ti -1c
.RI "uint8_t \fBstatus\fP = 0"
.br
.ti -1c
.RI "uint8_t \fBcodeErr\fP = 0"
.br
.ti -1c
.RI "int \fBsda\fP = \-1"
.br
.ti -1c
.RI "int \fBscl\fP = \-1"
.br
.ti -1c
.RI "uint32_t \fBspeed\fP = \fBFLPROG_I2CSPEED\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле \fBflprogI2C\&.h\fP строка \fB85\fP
.SH "Конструктор(ы)"
.PP 
.SS "FLProgVirtualI2C::FLProgVirtualI2C (\fBFLProgTCA9548A\fP * parentDevice, uint8_t chanelOnParent)"

.PP
См\&. определение в файле \fBflprogI2C\&.cpp\fP строка \fB516\fP
.SH "Методы"
.PP 
.SS "int FLProgVirtualI2C::available ()\fC [virtual]\fP"

.PP
Переопределяет метод предка \fBFLProgI2C\fP\&.
.PP
См\&. определение в файле \fBflprogI2C\&.cpp\fP строка \fB547\fP
.SS "bool FLProgVirtualI2C::begin ()\fC [virtual]\fP"

.PP
Переопределяет метод предка \fBFLProgI2C\fP\&.
.PP
См\&. определение в файле \fBflprogI2C\&.cpp\fP строка \fB522\fP
.SS "void FLProgVirtualI2C::beginTransmission (uint8_t addr)\fC [virtual]\fP"

.PP
Переопределяет метод предка \fBFLProgI2C\fP\&.
.PP
См\&. определение в файле \fBflprogI2C\&.cpp\fP строка \fB527\fP
.SS "bool FLProgVirtualI2C::checkBus ()\fC [virtual]\fP"

.PP
Переопределяет метод предка \fBFLProgI2C\fP\&.
.PP
См\&. определение в файле \fBflprogI2C\&.cpp\fP строка \fB572\fP
.SS "uint8_t FLProgVirtualI2C::endTransmission ()\fC [virtual]\fP"

.PP
Переопределяет метод предка \fBFLProgI2C\fP\&.
.PP
См\&. определение в файле \fBflprogI2C\&.cpp\fP строка \fB542\fP
.SS "int FLProgVirtualI2C::read ()\fC [virtual]\fP"

.PP
Переопределяет метод предка \fBFLProgI2C\fP\&.
.PP
См\&. определение в файле \fBflprogI2C\&.cpp\fP строка \fB552\fP
.SS "uint8_t FLProgVirtualI2C::requestFrom (uint8_t address, uint8_t quantity)\fC [virtual]\fP"

.PP
Переопределяет метод предка \fBFLProgI2C\fP\&.
.PP
См\&. определение в файле \fBflprogI2C\&.cpp\fP строка \fB557\fP
.SS "void FLProgVirtualI2C::resetSpeedFrom (uint32_t newSpeed)\fC [virtual]\fP"

.PP
Переопределяет метод предка \fBFLProgI2C\fP\&.
.PP
См\&. определение в файле \fBflprogI2C\&.cpp\fP строка \fB567\fP
.SS "void FLProgVirtualI2C::setSpeed (uint32_t newSpeed)\fC [virtual]\fP"

.PP
Переопределяет метод предка \fBFLProgI2C\fP\&.
.PP
См\&. определение в файле \fBflprogI2C\&.cpp\fP строка \fB562\fP
.SS "void FLProgVirtualI2C::write (const uint8_t * data, uint8_t quantity)\fC [virtual]\fP"

.PP
Переопределяет метод предка \fBFLProgI2C\fP\&.
.PP
См\&. определение в файле \fBflprogI2C\&.cpp\fP строка \fB532\fP
.SS "void FLProgVirtualI2C::write (uint8_t data)\fC [virtual]\fP"

.PP
Переопределяет метод предка \fBFLProgI2C\fP\&.
.PP
См\&. определение в файле \fBflprogI2C\&.cpp\fP строка \fB537\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для FLProg Utilites из исходного текста\&.
