.TH "FLProgI2cStepWorkSensor" 3 "Чт 23 Фев 2023" "Version 1" "FLProg Utilites" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLProgI2cStepWorkSensor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <flprogI2C_sensorsBasic\&.h>\fP
.PP
Базовые классы:\fBFLProgI2cBasicSensor\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "void \fBread\fP ()"
.br
.ti -1c
.RI "void \fBsetReadPeriod\fP (uint32_t period)"
.br
.in -1c

Открытые члены унаследованные от \fBFLProgI2cBasicSensor\fP
.in +1c
.ti -1c
.RI "uint8_t \fBgetError\fP ()"
.br
.in -1c
.SS "Защищенные члены"

.in +1c
.ti -1c
.RI "virtual void \fBreadSensor\fP ()"
.br
.ti -1c
.RI "void \fBcheckDelay\fP ()"
.br
.ti -1c
.RI "void \fBcheckReadPeriod\fP ()"
.br
.ti -1c
.RI "void \fBgotoStepWithDelay\fP (uint8_t newStep, uint32_t delay)"
.br
.ti -1c
.RI "void \fBcheckNeededRead\fP ()"
.br
.in -1c
.SS "Защищенные данные"

.in +1c
.ti -1c
.RI "uint32_t \fBstartDelay\fP"
.br
.ti -1c
.RI "uint32_t \fBsizeDelay\fP"
.br
.ti -1c
.RI "uint8_t \fBstepAfterDelay\fP"
.br
.ti -1c
.RI "bool \fBisNeededRead\fP = true"
.br
.ti -1c
.RI "uint32_t \fBreadPeriod\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBstartReadPeriod\fP = 0"
.br
.ti -1c
.RI "uint8_t \fBstep\fP = \fBFLPROG_SENSOR_WAITING_READ_STEP\fP"
.br
.in -1c

Защищенные данные унаследованные от \fBFLProgI2cBasicSensor\fP
.in +1c
.ti -1c
.RI "\fBFLProgI2C\fP * \fBi2cDevice\fP"
.br
.ti -1c
.RI "uint8_t \fBaddres\fP"
.br
.ti -1c
.RI "uint32_t \fBspeed\fP = \fBFLPROG_I2CSPEED\fP"
.br
.ti -1c
.RI "uint8_t \fBcodeError\fP = \fBFLPROG_SENSOR_NOT_ERROR\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле \fBflprogI2C_sensorsBasic\&.h\fP строка \fB17\fP
.SH "Методы"
.PP 
.SS "void FLProgI2cStepWorkSensor::checkDelay ()\fC [protected]\fP"

.PP
См\&. определение в файле \fBflprogI2C_sensorsBasic\&.cpp\fP строка \fB3\fP
.SS "void FLProgI2cStepWorkSensor::checkNeededRead ()\fC [protected]\fP"

.PP
См\&. определение в файле \fBflprogI2C_sensorsBasic\&.cpp\fP строка \fB45\fP
.SS "void FLProgI2cStepWorkSensor::checkReadPeriod ()\fC [protected]\fP"

.PP
См\&. определение в файле \fBflprogI2C_sensorsBasic\&.cpp\fP строка \fB25\fP
.SS "void FLProgI2cStepWorkSensor::gotoStepWithDelay (uint8_t newStep, uint32_t delay)\fC [protected]\fP"

.PP
См\&. определение в файле \fBflprogI2C_sensorsBasic\&.cpp\fP строка \fB37\fP
.SS "void FLProgI2cStepWorkSensor::read ()"

.PP
См\&. определение в файле \fBflprogI2C_sensorsBasic\&.cpp\fP строка \fB15\fP
.SS "virtual void FLProgI2cStepWorkSensor::readSensor ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
См\&. определение в файле \fBflprogI2C_sensorsBasic\&.h\fP строка \fB24\fP
.SS "void FLProgI2cStepWorkSensor::setReadPeriod (uint32_t period)"

.PP
См\&. определение в файле \fBflprogI2C_sensorsBasic\&.cpp\fP строка \fB20\fP
.SH "Данные класса"
.PP 
.SS "bool FLProgI2cStepWorkSensor::isNeededRead = true\fC [protected]\fP"

.PP
См\&. определение в файле \fBflprogI2C_sensorsBasic\&.h\fP строка \fB32\fP
.SS "uint32_t FLProgI2cStepWorkSensor::readPeriod = 0\fC [protected]\fP"

.PP
См\&. определение в файле \fBflprogI2C_sensorsBasic\&.h\fP строка \fB33\fP
.SS "uint32_t FLProgI2cStepWorkSensor::sizeDelay\fC [protected]\fP"

.PP
См\&. определение в файле \fBflprogI2C_sensorsBasic\&.h\fP строка \fB30\fP
.SS "uint32_t FLProgI2cStepWorkSensor::startDelay\fC [protected]\fP"

.PP
См\&. определение в файле \fBflprogI2C_sensorsBasic\&.h\fP строка \fB29\fP
.SS "uint32_t FLProgI2cStepWorkSensor::startReadPeriod = 0\fC [protected]\fP"

.PP
См\&. определение в файле \fBflprogI2C_sensorsBasic\&.h\fP строка \fB34\fP
.SS "uint8_t FLProgI2cStepWorkSensor::step = \fBFLPROG_SENSOR_WAITING_READ_STEP\fP\fC [protected]\fP"

.PP
См\&. определение в файле \fBflprogI2C_sensorsBasic\&.h\fP строка \fB35\fP
.SS "uint8_t FLProgI2cStepWorkSensor::stepAfterDelay\fC [protected]\fP"

.PP
См\&. определение в файле \fBflprogI2C_sensorsBasic\&.h\fP строка \fB31\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для FLProg Utilites из исходного текста\&.
