.TH "src/i2c/flprogI2C.h" 3 "Чт 23 Фев 2023" "Version 1" "FLProg Utilites" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/i2c/flprogI2C.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Arduino\&.h'\fP
.br
\fC#include <Wire\&.h>\fP
.br
\fC#include 'flprogUtilites\&.h'\fP
.br
\fC#include 'flprogI2C_sensorsBasic\&.h'\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBFLProgI2C\fP"
.br
.ti -1c
.RI "class \fBFLProgTCA9548A\fP"
.br
.ti -1c
.RI "class \fBFLProgVirtualI2C\fP"
.br
.in -1c
.SS "Макросы"

.in +1c
.ti -1c
.RI "#define \fBFLPROG_I2CSPEED\fP   400000UL;"
.br
.in -1c
.SH "Макросы"
.PP 
.SS "#define FLPROG_I2CSPEED   400000UL;"

.PP
См\&. определение в файле \fBflprogI2C\&.h\fP строка \fB9\fP
.SH "Автор"
.PP 
Автоматически создано Doxygen для FLProg Utilites из исходного текста\&.
