.TH "Содержание директории src/i2c" 3 "Чт 23 Фев 2023" "Version 1" "FLProg Utilites" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории src/i2c
.SH SYNOPSIS
.br
.PP
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBflprogI2C\&.cpp\fP"
.br
.ti -1c
.RI "файл \fBflprogI2C\&.h\fP"
.br
.ti -1c
.RI "файл \fBflprogI2C_sensorsBasic\&.cpp\fP"
.br
.ti -1c
.RI "файл \fBflprogI2C_sensorsBasic\&.h\fP"
.br
.in -1c
