.TH "Содержание директории src/variant/arduino" 3 "Чт 23 Фев 2023" "Version 1" "FLProg Utilites" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории src/variant/arduino
.SH SYNOPSIS
.br
.PP
.SS "Директории"

.in +1c
.ti -1c
.RI "директория \fBavr\fP"
.br
.ti -1c
.RI "директория \fBdue\fP"
.br
.in -1c
