.TH "src/uart/hardwareUart/hardwareUartDUE/hardwareUartDUE.h" 3 "Чт 23 Фев 2023" "Version 1" "FLProg Utilites" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/uart/hardwareUart/hardwareUartDUE/hardwareUartDUE.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Arduino\&.h'\fP
.br
\fC#include 'flprogUtilites\&.h'\fP
.br

.SH "Автор"
.PP 
Автоматически создано Doxygen для FLProg Utilites из исходного текста\&.
